import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/providers/theme-provider";
import Header from "@/components/header/Header";
import Sidebar from "@/components/header/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Notion Clone",
  description: "Generated by create next app",
};
const  RootLayout=({
  children,
}: Readonly<{
  children: ReactNode;
}>) =>{
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            <div className="flex min-h-screen">
              <Sidebar />
              <div className="flex-1 p-4 bg-gray-100 overflow-y-auto scrollbar-hide">
                {children}
              </div>
            </div>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
export default RootLayout;